### ISSUE TITLE
Compatibility for struts2 v2.5.x

### ISSUE THREAD

**Issue by pablocossioabastoflor** [aleksandr-m/struts2-actionflow#8]
I'm getting this exception after update struts2 to 2.5.10.1

java.lang.NoClassDefFoundError: org/apache/struts2/dispatcher/ServletActionRedirectResult
	com.amashchenko.struts2.actionflow.ActionFlowConfigBuilder.createFlowMap(ActionFlowConfigBuilder.java:253)
	com.amashchenko.struts2.actionflow.ActionFlowInterceptor.initFlowConfiguration(ActionFlowInterceptor.java:465)
	com.amashchenko.struts2.actionflow.ActionFlowInterceptor.intercept(ActionFlowInterceptor.java:186)
	com.opensymphony.xwork2.DefaultActionInvocation.invoke(DefaultActionInvocation.java:247)
	org.apache.struts2.factory.StrutsActionProxy.execute(StrutsActionProxy.java:54)
	org.apache.struts2.dispatcher.Dispatcher.serviceAction(Dispatcher.java:564)
	org.apache.struts2.dispatcher.ExecuteOperations.executeAction(ExecuteOperations.java:81)
	org.apache.struts2.dispatcher.filter.StrutsPrepareAndExecuteFilter.doFilter(StrutsPrepareAndExecuteFilter.java:143)

Thank you in advance.

**Comment by aleksandr-m** [comment]
@pablocossioabastoflor Current version is not compatible with 2.5. I'll take a look, but can't promise anything.

**Comment by aleksandr-m** [comment]
@pablocossioabastoflor Take a look at [feature/2.5.x](https://github.com/aleksandr-m/struts2-actionflow/tree/feature/2.5.x) branch.
